### PR TITLE
Add driver manifest to main

### PR DESCRIPTION
**Pull request by mescudi21**

### CODE REVIEW

**Review by vtorhonen — CHANGES_REQUESTED** [review]
Please also update README to use this manifest (and not from previous branches).

**Comment by mescudi21** [comment]
> Please also update README to use this manifest (and not from previous branches).

Thanks, removed old `alpha` paths

**Comment by ajmyyra** [comment]
Seems good now!

**Review by ajmyyra — APPROVED** [review]
LGTM.

**Pull request merged**
